config/routes.rb
Rails.application.routes.draw do
  resources :devices, only: [:index]
  post '/action', to: 'devices#action'
  root to: 'devices#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  protect_from_forgery with: :null_session

  # GET /devices
  # GET /devices.json
  def index
    @devices =Device.where("last_message_time >= TIMESTAMP WITH TIME ZONE '#{Time.zone.now - 120}'")
    respond_to do |format|
      format.html
      format.js
    end
  end

  def action
    device = Device.find_or_create_by(device_id: params[:device_id])
    if device.device_ip
      unless device.device_ip == request.remote_ip
        device.message = "Error! Same id for 2 or more devices! Last good ip was #{device.device_ip}"
      else
        device.email = params[:email] unless device.email == params[:email]
        device.last_message_time = Time.now
        device.message = params[:message] unless device.message == params[:message]
      end
    else
      device.device_ip = request.remote_ip
      device.message = params[:message]
      device.email = params[:email]
      device.last_message_time = Time.zone.now
    end
    device.save
    render json: { "status": 200, "message": "I take it! All is ok" }
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:device_id, :email, :message, :last_message_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_device.html.slim
.col-md-4
  .card.mb-4
    .card-header
        h5.card-title
          | ID #{device.device_id}
    .card-body
      table.table-bordered[style="width: 100%"]
        thead
          th.text-center
            | Email
          th.text-center
            | Message
          th.text-center
            | IP
        tbody
          td.text-center
            p  #{device.email}
          td.text-center
            p  #{device.message}
          td.text-center
            p  #{device.device_ip}

app/views/devices/_form.html.erb
<%= form_with(model: device, local: true) do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :device_id %>
    <%= form.number_field :device_id, id: :device_device_id %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :device_email %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message, id: :device_message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.slim
javascript:
    window.onload = function(){
          setInterval(function(){
            console.log('!!!!');
            $('#time_div').load("/devices");
      }, 20000);
    };

#time_div
  h2.text-center
    | Dashboard
  .row
    = render @devices

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device:</strong>
  <%= @device.device_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @device.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @device.message %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RobatsLabServer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>